# Schedule

```{r, class.source = 'fold-hide'}
2 + 2
```


```{r, class.source = 'foldable'}
5 + 5
```


test info

```{r schedule, echo=FALSE, message=F, warning=F}
library(tidyverse)
kableExtra::kbl(data.frame("Week" = 1:5, 
                           "Date" = c("June 27", "July 04", "July 11", "July 18", "July 25"),
                           "Mon" = c("<b>test</b>", "*test*", "**test**", "`test`", "test"),
                           "Tue" = c(""),
                           "Wed" = c(""),
                           "Thu" = c(1:5),
                           "Fri" = c("Testing things out with \n longer text", "", "", "", ""))) %>%
    #kableExtra::kable_paper("striped", full_width = T) %>%
    #column_spec(5:7, bold = T) %>%
    #kableExtra::row_spec(1, bold = T, color = "white", background = "grey")
  #kable_material(c("striped", "hover"))
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), position = "center")


```

test

Kable info for tables:

https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

https://bookdown.org/yihui/rmarkdown-cookbook/tables.html

http://haozhu233.github.io/kableExtra/best_practice_for_newline_in_latex_table.pdf
^info about linebreaks
